name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  dist-job:
    name: Build distribution
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.40
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cpanm Neo4j::Client --dev
          cpanm --cpanfile cpanfile --installdeps --skip-satisfied \
            --with-recommends --with-configure --with-develop .
      - name: Run unit tests
        run: |
          perl Makefile.PL
          make
          make test
          make manifypods
        env:
          PERL_MM_USE_DEFAULT: 1
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
          NO_NETWORK_TESTING: 1
      - name: Build distribution
        run: |
          rm -f Neo4j-Bolt-*
          make distdir
          mv -v Neo4j-Bolt-* build_dir
      - uses: actions/upload-artifact@v4
        with:
          name: build_dir
          path: build_dir
          retention-days: 1
          include-hidden-files: true  # .sample.cypher

  test-job:
    needs: dist-job
    runs-on: ubuntu-latest
    name: "Perl ${{ matrix.perl }} / Neo4j ${{ matrix.neo4j }}"
    strategy:
      matrix:
        include:
          - neo4j: "2025"  # Bolt v5/v6
            perl: "5.40"
          - neo4j: "5.26"  # Bolt v5
            perl: "5.16"
          - neo4j: "4.4"   # Bolt v4
            perl: "5.42"
          - neo4j: "3.5"   # Bolt v3
            perl: "5.36"
      fail-fast: false
    env:
      CI: 1
      TEST_NEO4J_PASSWORD: xkcd_792
    steps:
      - name: Install Neo4j
        id: install
        uses: johannessen/actions-install-neo4j@v1
        with:
          neo4j-version: ${{ matrix.neo4j }}
          password: ${{ env.TEST_NEO4J_PASSWORD }}
      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          install-modules: ExtUtils::MakeMaker~6.78
          enable-modules-cache: false
      - name: Get distribution
        uses: actions/download-artifact@v4
        with:
          name: build_dir
          path: .
      - name: Install distribution dependencies
        run: |
          cpanm Neo4j::Client --dev
          cpanm -nq --installdeps --skip-satisfied .
      - name: Version info
        run: |
          curl -s http://localhost:7474/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          curl -s http://localhost:7474/db/data/ -u "neo4j:$TEST_NEO4J_PASSWORD" | grep neo4j_version || true
          ls | grep --max-count=1 neo4j-community || true
          which perl
          perl -V
          cat neo4j-javahome
      - name: Build
        run: |
          echo y$'\n'$'\n'"neo4j"$'\n'"$TEST_NEO4J_PASSWORD"$'\n'y | perl Makefile.PL
          cat t/neo_info
          make
      - name: Test
        run: |
          export JAVA_HOME="$(cat neo4j-javahome)"
          neo4j-community-$NEO4J/bin/cypher-shell -u neo4j -p "$TEST_NEO4J_PASSWORD" < .sample.cypher
          make test
        env:
          AUTOMATED_TESTING: 1
          NONINTERACTIVE_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
          AUTHOR_TESTING: 1
          NEO4J: ${{ steps.install.outputs.neo4j-version }}
